Now at 33 typescript errors
doenet-dev-1     | [22:35:30] [@snowpack/plugin-typescript] src/Tools/test/example-app/src/api.ts(3,26): error TS7016: Could not find a declaration file for module '@pm-react-example/shared'. '/home/node/workspace/src/Tools/test/shared/index.js' implicitly has an 'any' type.
doenet-dev-1     | [22:35:30] [@snowpack/plugin-typescript] src/Tools/test/example-app/src/components/NavBar.tsx(5,10): error TS2305: Module '"react-router"' has no exported member 'RouteComponentProps'.
doenet-dev-1     | src/Tools/test/example-app/src/components/NavBar.tsx(16,22): error TS2769: No overload matches this call.
doenet-dev-1     |   Overload 1 of 2, '(props: { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; style?: CSSProperties | ((props: { ...; }) => CSSProperties) | undefined; ... 265 more ...; end?: boolean | undefined; } & { ...; } & { ...; }): ReactElement<...>', gave the following error.
doenet-dev-1     |     Type '{ children: string; to: string; exact: true; activeClassName: string; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     |       Property 'exact' does not exist on type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     |   Overload 2 of 2, '(props: StyledComponentPropsWithAs<ForwardRefExoticComponent<NavLinkProps & RefAttributes<HTMLAnchorElement>>, any, {}, never, ForwardRefExoticComponent<...>, ForwardRefExoticComponent<...>>): ReactElement<...>', gave the following error.
doenet-dev-1     |     Type '{ children: string; to: string; exact: true; activeClassName: string; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     |       Property 'exact' does not exist on type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     | src/Tools/test/example-app/src/components/NavBar.tsx(17,29): error TS2769: No overload matches this call.
doenet-dev-1     |   Overload 1 of 2, '(props: { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; style?: CSSProperties | ((props: { ...; }) => CSSProperties) | undefined; ... 265 more ...; end?: boolean | undefined; } & { ...; } & { ...; }): ReactElement<...>', gave the following error.
doenet-dev-1     |     Type '{ children: string; to: string; activeClassName: string; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     |       Property 'activeClassName' does not exist on type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     |   Overload 2 of 2, '(props: StyledComponentPropsWithAs<ForwardRefExoticComponent<NavLinkProps & RefAttributes<HTMLAnchorElement>>, any, {}, never, ForwardRefExoticComponent<...>, ForwardRefExoticComponent<...>>): ReactElement<...>', gave the following error.
doenet-dev-1     |     Type '{ children: string; to: string; activeClassName: string; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     |       Property 'activeClassName' does not exist on type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     | src/Tools/test/example-app/src/components/NavBar.tsx(18,31): error TS2769: No overload matches this call.
doenet-dev-1     |   Overload 1 of 2, '(props: { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; style?: CSSProperties | ((props: { ...; }) => CSSProperties) | undefined; ... 265 more ...; end?: boolean | undefined; } & { ...; } & { ...; }): ReactElement<...>', gave the following error.
doenet-dev-1     |     Type '{ children: string; to: string; activeClassName: string; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     |       Property 'activeClassName' does not exist on type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     |   Overload 2 of 2, '(props: StyledComponentPropsWithAs<ForwardRefExoticComponent<NavLinkProps & RefAttributes<HTMLAnchorElement>>, any, {}, never, ForwardRefExoticComponent<...>, ForwardRefExoticComponent<...>>): ReactElement<...>', gave the following error.
doenet-dev-1     |     Type '{ children: string; to: string; activeClassName: string; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     |       Property 'activeClassName' does not exist on type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     | src/Tools/test/example-app/src/components/NavBar.tsx(19,28): error TS2769: No overload matches this call.
doenet-dev-1     |   Overload 1 of 2, '(props: { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; style?: CSSProperties | ((props: { ...; }) => CSSProperties) | undefined; ... 265 more ...; end?: boolean | undefined; } & { ...; } & { ...; }): ReactElement<...>', gave the following error.
doenet-dev-1     |     Type '{ children: string; to: string; activeClassName: string; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     |       Property 'activeClassName' does not exist on type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     |   Overload 2 of 2, '(props: StyledComponentPropsWithAs<ForwardRefExoticComponent<NavLinkProps & RefAttributes<HTMLAnchorElement>>, any, {}, never, ForwardRefExoticComponent<...>, ForwardRefExoticComponent<...>>): ReactElement<...>', gave the following error.
doenet-dev-1     |     Type '{ children: string; to: string; activeClassName: string; }' is not assignable to type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     |       Property 'activeClassName' does not exist on type 'IntrinsicAttributes & { children?: ReactNode | ((props: { isActive: boolean; }) => ReactNode); dir?: string | undefined; slot?: string | undefined; ... 266 more ...; end?: boolean | undefined; } & { ...; } & { ...; }'.
doenet-dev-1     | src/Tools/test/example-app/src/components/WrappedRoute.tsx(2,29): error TS2305: Module '"react-router"' has no exported member 'RouteComponentProps'.
doenet-dev-1     | src/Tools/test/example-app/src/components/WrappedRoute.tsx(7,57): error TS2694: Namespace 'React' has no exported member 'StatelessComponent'.
doenet-dev-1     | src/Tools/test/example-app/src/components/WrappedRoute.tsx(28,20): error TS2322: Type '{ render: (props: RouteComponentProps<any>) => Element; caseSensitive?: boolean | undefined; children?: ReactNode; element?: ReactNode; index?: boolean | undefined; path?: string | undefined; }' is not assignable to type 'IntrinsicAttributes & (PathRouteProps | LayoutRouteProps | IndexRouteProps)'.
doenet-dev-1     |   Property 'render' does not exist on type 'IntrinsicAttributes & (PathRouteProps | LayoutRouteProps | IndexRouteProps)'.
doenet-dev-1     | src/Tools/test/example-app/src/components/WrappedRoute.tsx(31,20): error TS2322: Type '{ render: (props: RouteComponentProps<any>) => Element; caseSensitive?: boolean | undefined; children?: ReactNode; element?: ReactNode; index?: boolean | undefined; path?: string | undefined; }' is not assignable to type 'IntrinsicAttributes & (PathRouteProps | LayoutRouteProps | IndexRouteProps)'.
doenet-dev-1     |   Property 'render' does not exist on type 'IntrinsicAttributes & (PathRouteProps | LayoutRouteProps | IndexRouteProps)'.
doenet-dev-1     | [22:35:30] [@snowpack/plugin-typescript] src/Tools/test/example-app/src/components/editor/Editor.tsx(2,22): error TS7016: Could not find a declaration file for module 'lodash.debounce'. '/home/node/workspace/node_modules/lodash.debounce/index.js' implicitly has an 'any' type.
doenet-dev-1     |   Try `npm i --save-dev @types/lodash.debounce` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash.debounce';`
doenet-dev-1     | src/Tools/test/example-app/src/components/editor/Editor.tsx(8,43): error TS2305: Module '"@pm-react-example/full-v2"' has no exported member 'Collab'.
doenet-dev-1     | src/Tools/test/example-app/src/document-api.ts(1,75): error TS7016: Could not find a declaration file for module '@pm-react-example/shared'. '/home/node/workspace/src/Tools/test/shared/index.js' implicitly has an 'any' type.
doenet-dev-1     | src/Tools/test/example-app/src/pages/FullV1Page.tsx(2,22): error TS7016: Could not find a declaration file for module 'lodash.debounce'. '/home/node/workspace/node_modules/lodash.debounce/index.js' implicitly has an 'any' type.
doenet-dev-1     |   Try `npm i --save-dev @types/lodash.debounce` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash.debounce';`
doenet-dev-1     | src/Tools/test/example-app/src/routes.tsx(2,25): error TS2305: Module '"react-router-dom"' has no exported member 'Redirect'.
doenet-dev-1     | src/Tools/test/example-app/src/routes.tsx(2,35): error TS2305: Module '"react-router-dom"' has no exported member 'Switch'.
doenet-dev-1     | src/Tools/test/example-app/src/routes.tsx(14,21): error TS2322: Type '{ exact: true; path: string; component: (props: IProps) => Element; }' is not assignable to type 'IntrinsicAttributes & IWrappedRoute'.
doenet-dev-1     |   Property 'exact' does not exist on type 'IntrinsicAttributes & IWrappedRoute'.
doenet-dev-1     | src/Tools/test/example-app/src/routes.tsx(15,21): error TS2322: Type '{ exact: true; path: string; component: (props: IProps) => Element; }' is not assignable to type 'IntrinsicAttributes & IWrappedRoute'.
doenet-dev-1     |   Property 'exact' does not exist on type 'IntrinsicAttributes & IWrappedRoute'.
doenet-dev-1     | src/Tools/test/example-app/src/routes.tsx(16,21): error TS2322: Type '{ exact: true; path: string; component: (props: IProps) => Element; }' is not assignable to type 'IntrinsicAttributes & IWrappedRoute'.
doenet-dev-1     |   Property 'exact' does not exist on type 'IntrinsicAttributes & IWrappedRoute'.
doenet-dev-1     | src/Tools/test/example-app/src/routes.tsx(17,21): error TS2322: Type '{ exact: true; path: string; component: (props: IProps) => Element; }' is not assignable to type 'IntrinsicAttributes & IWrappedRoute'.
doenet-dev-1     |   Property 'exact' does not exist on type 'IntrinsicAttributes & IWrappedRoute'.
doenet-dev-1     | src/Tools/test/example-app/src/stores/AuthStore.ts(3,31): error TS7016: Could not find a declaration file for module '@pm-react-example/shared'. '/home/node/workspace/src/Tools/test/shared/index.js' implicitly has an 'any' type.
doenet-dev-1     | src/Tools/test/example-app/src/stores/DocumentStore.ts(10,8): error TS7016: Could not find a declaration file for module '@pm-react-example/shared'. '/home/node/workspace/src/Tools/test/shared/index.js' implicitly has an 'any' type.
doenet-dev-1     | src/Tools/test/example-app/src/stores/DocumentStore.ts(71,20): error TS7006: Parameter 'd' implicitly has an 'any' type.
doenet-dev-1     | src/Tools/test/example-app/src/stores/EditorStore.ts(2,33): error TS7016: Could not find a declaration file for module '@pm-react-example/shared'. '/home/node/workspace/src/Tools/test/shared/index.js' implicitly has an 'any' type.
doenet-dev-1     | src/Tools/test/example-app/src/stores/EditorStore.ts(21,5): error TS2532: Object is possibly 'undefined'.
doenet-dev-1     | src/Tools/test/example-app/src/stores/EditorStore.ts(22,12): error TS2532: Object is possibly 'undefined'.
doenet-dev-1     | src/Tools/test/prosemirror-react/context/PluginsProvider.ts(1,27): error TS2691: An import path cannot end with a '.ts' extension. Consider importing '../core/pm/plugin.js' instead.
doenet-dev-1     | src/Tools/test/prosemirror-react/extensions/base/pm-plugins/state.ts(2,27): error TS2691: An import path cannot end with a '.ts' extension. Consider importing '../../../core/pm/plugin.js' instead.
doenet-dev-1     | src/Tools/test/prosemirror-react/extensions/blockquote/nodeviews/BlockQuoteView.ts(24,5): error TS2322: Type 'BlockQuoteView' is not assignable to type 'NodeView'.
doenet-dev-1     |   Types of property 'dom' are incompatible.
doenet-dev-1     |     Type 'HTMLElement | undefined' is not assignable to type 'Node'.
doenet-dev-1     |       Type 'undefined' is not assignable to type 'Node'.
doenet-dev-1     | src/Tools/test/prosemirror-react/extensions/blockquote/pm-utils/findBlockQuote.ts(9,15): error TS2315: Type 'Selection' is not generic.
doenet-dev-1     | src/Tools/test/prosemirror-react/react/ReactNodeView.tsx(24,3): error TS2416: Property 'dom' in type 'ReactNodeView<P, A>' is not assignable to the same property in base type 'NodeView'.
doenet-dev-1     |   Type 'HTMLElement | undefined' is not assignable to type 'Node'.
doenet-dev-1     |     Type 'undefined' is not assignable to type 'Node'.
doenet-dev-1     | src/Tools/test/prosemirror-react/react/ReactNodeView.tsx(33,3): error TS2416: Property 'contentDOM' in type 'ReactNodeView<P, A>' is not assignable to the same property in base type 'NodeView'.
doenet-dev-1     |   Type 'Node | undefined' is not assignable to type 'HTMLElement | null | undefined'.
doenet-dev-1     |     Type 'Node' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 227 more.
doenet-dev-1     | [22:35:30] [@snowpack/plugin-typescript] src/Tools/test/prosemirror-react/react/ReactNodeView.tsx(163,3): error TS2416: Property 'update' in type 'ReactNodeView<P, A>' is not assignable to the same property in base type 'NodeView'.
doenet-dev-1     |   Type '(node: Node, _decorations: Decoration[]) => boolean' is not assignable to type '(node: Node, decorations: readonly Decoration[], innerDecorations: DecorationSource) => boolean'.
doenet-dev-1     |     Types of parameters '_decorations' and 'decorations' are incompatible.
doenet-dev-1     |       The type 'readonly Decoration[]' is 'readonly' and cannot be assigned to the mutable type 'Decoration[]'.
doenet-dev-1     | [22:35:30] [@snowpack/plugin-typescript] 9:34:30 PM - Found 33 errors. Watching for file changes.